In [15]:
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

from models import Pi, Sigma
from datasets import PiDataset, SigmaDataset
from retrictions import get_F

In [16]:
model = Pi(poly_order=3)
model.w = torch.nn.Parameter(torch.tensor([0.5, 0.2, 0.6]))

In [22]:
get_F(model.w, 0)

array([[-1.  ,  0.8 , -0.12]], dtype=float32)

In [25]:
x1 = get_F(model.w, 0)
x1

array([[-1.  ,  0.8 , -0.12]], dtype=float32)

In [27]:
x2 = np.array([[-1, 0.8, -0.12]])
x2

array([[-1.  ,  0.8 , -0.12]])

In [34]:
np.allclose(x1, x2)

True

In [33]:
get_F(model.w, 0) == np.array([[-1, 0.8, -0.12]]).astype(np.float32)

array([[ True,  True, False]])

# Training PI Model

In [6]:
# dataset = PiDataset(coeff=[1.0, 2.9, -0.8, -6.3, -3.6], size=2_048)
# dataloader = DataLoader(dataset, batch_size=256, num_workers=2)
# model = Pi(poly_order=4)

In [7]:
# epochs = 5_000
# optimizer = optim.Adam(model.parameters())
# criterion = nn.MSELoss()
# writer = SummaryWriter('./runs/PI-1')

In [8]:
# b = 1
# for epoch in range(epochs):
#     for input, target in dataloader:
#         optimizer.zero_grad()
#         output = model(input)
#         loss = criterion(output, target)
#         loss.backward()
#         optimizer.step()
#         writer.add_scalar('Loss', loss.item(), b)
#         writer.add_scalar('W1', model.w[0, 0], b)
#         writer.add_scalar('W2', model.w[0, 1], b)
#         writer.add_scalar('W3', model.w[0, 2], b)
#         writer.add_scalar('W4', model.w[0, 3], b)
#         b += 1

# Training Sigma Model

In [9]:
# dataset = SigmaDataset(coeff=[1.0, 2.9, -0.8, -6.3, -3.6], size=2_048)
# dataloader = DataLoader(dataset, batch_size=256, num_workers=2)
# model = Sigma(poly_order=4)

In [10]:
# epochs = 5_000
# optimizer = optim.Adam(model.parameters())
# criterion = nn.MSELoss()
# writer = SummaryWriter('./runs/SIGMA-6')

In [11]:
# b = 1
# for epoch in range(epochs):
#     for input, target in dataloader:
#         optimizer.zero_grad()
#         output = model(input)
#         loss = criterion(output, target)
#         loss.backward()
#         optimizer.step()
#         writer.add_scalar('Loss', loss.item(), b)
#         writer.add_scalar('W1', model.w[0, 0], b)
#         writer.add_scalar('W2', model.w[0, 1], b)
#         writer.add_scalar('W3', model.w[0, 2], b)
#         writer.add_scalar('W4', model.w[0, 3], b)
#         b += 1